force-app/main/default/objects/Case_History__c/Case_History__c.object-meta.xml
<CustomObject>
    <label>Case History</label>
    <nameField>
        <label>Case History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_History__c/fields/Case_Request__c.field-meta.xml
<CustomField>
    <fullName>Case_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Request</label>
    <referenceTo>Case_Request__c</referenceTo>
    <relationshipLabel>Case Histories</relationshipLabel>
    <relationshipName>Case_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/SLA_Met__c.field-meta.xml
<CustomField>
    <fullName>SLA_Met__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SLA Met</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_History__c/fields/Time_Closed__c.field-meta.xml
<CustomField>
    <fullName>Time_Closed__c</fullName>
    <label>Time Closed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <description>Logging customer support requests.</description>
    <label>Case Request</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Case Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/SLA_Deadline__c.field-meta.xml
<CustomField>
    <fullName>SLA_Deadline__c</fullName>
    <description>Deadline for resolving the request.</description>
    <inlineHelpText>Date and time limit to resolve the issue according to SLA.</inlineHelpText>
    <label>SLA Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the request.</description>
    <inlineHelpText>Choose the appropriate status for the progress of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseRequestManager.cls
@RestResource(urlMapping='/Case_Request__c/*')
global with sharing class CaseRequestManager {
    
    @HttpGet
    global static void getCaseRequest() {
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response;
        
        if (request == null || String.isBlank(request.requestURI)) {
            
            response.responseBody = Blob.valueOf(formatErrorResponse('Bad Request', 'Invalid request URI.'));
            response.statusCode = 400;
            return;
        }
        
        String caseRequestId = extractCaseRequestId(request.requestURI);
        
        if (String.isBlank(caseRequestId)) {
            
            response.responseBody = Blob.valueOf(formatErrorResponse('Bad Request', 'Case request id can\'t be null.'));
            response.statusCode = 400;
            return;
        }
        
        try {
            Case_Request__c result = findCaseRequest(caseRequestId);
            
            response.responseBody = Blob.valueOf(formatSuccessResponse(result));
            response.statusCode = 200;
            
        } catch (Exception e) {
            
            response.responseBody = Blob.valueOf(formatErrorResponse('Not Found', 'Case Request ID not found or invalid.'));
            response.statusCode = 404;
        }
    }
    
    private static String extractCaseRequestId(String requestURI) {
        return requestURI.substring(requestURI.lastIndexOf('/') + 1);
    }
    
    private static Case_Request__c findCaseRequest(String caseRequestId) {
        return [SELECT CreatedDate, Status__c, SLA_Deadline__c,  
            (SELECT SLA_Met__c, Time_Closed__c  
                FROM Case_Histories__r  
                ORDER BY CreatedDate DESC LIMIT 1)  
        FROM Case_Request__c 
        WHERE Id = :caseRequestId WITH SECURITY_ENFORCED];
    }
    
    private static String formatSuccessResponse(Case_Request__c result) {
        
        ResponseDto dto = new ResponseDto(
            result.createdDate,
        result.SLA_Deadline__c,
        result.Status__c,
        result.Case_Histories__r.isEmpty() ? null : result.Case_Histories__r[0].SLA_Met__c,
        result.Case_Histories__r.isEmpty() ? null : result.Case_Histories__r[0].Time_Closed__c
            );
        
        return JSON.serializePretty(dto);
    }
    
    private static String formatErrorResponse(String errorMessage, String message) {
        return JSON.serializePretty(new Map<String, Object>{
            'error' => errorMessage,
            'message' => message
        });
    }
}