force-app/main/default/objects/Case_History__c/Case_History__c.object-meta.xml
<CustomObject>
    <label>Case History</label>
    <nameField>
        <label>Case History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_History__c/fields/Case_Request__c.field-meta.xml
<CustomField>
    <fullName>Case_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Request</label>
    <referenceTo>Case_Request__c</referenceTo>
    <relationshipLabel>Case Histories</relationshipLabel>
    <relationshipName>Case_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <description>Logging customer support requests.</description>
    <label>Case Request</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Case Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Full details of the support request.</description>
    <inlineHelpText>Describe the issue encountered with as much detail as possible.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Request priority.</description>
    <inlineHelpText>Select the urgency level of the request.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Resolution_Notes__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Notes__c</fullName>
    <description>Details on how the support request was resolved.</description>
    <inlineHelpText>Provide a clear explanation of the solution applied, actions taken and any relevant information.</inlineHelpText>
    <label>Resolution Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the request.</description>
    <inlineHelpText>Choose the appropriate status for the progress of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Support request title.</description>
    <inlineHelpText>Provide a brief summary of the issue.</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseRequestTriggerTest.cls
@isTest
private class CaseRequestTriggerTest {
    
    @isTest
    static void shouldCreateCaseHistoryWhenCaseRequestClosed() {
        Case_Request__c caseRequest = new Case_Request__c();
        caseRequest.Subject__c = 'Test Case';
        caseRequest.Description__c = 'Testing case closed';
        caseRequest.Priority__c = 'Medium';
        
        insert caseRequest;
        
        Test.startTest();
        
        Case_Request__c caseToUpdate = [SELECT Id, Status__c FROM Case_Request__c LIMIT 1];
        caseToUpdate.Status__c = 'Closed';
        caseToUpdate.Resolution_Notes__c = 'Notes';
        
        update caseToUpdate;
        
        Case_History__c caseHistory = [SELECT Id FROM Case_History__c WHERE Case_Request__c = :caseToUpdate.Id LIMIT 1];
        Test.stopTest();
        
        System.assertNotEquals(null, caseHistory, 'Case history should be created.');
    }
    
    @isTest
    static void shouldNotCreateCaseHistoryWhenCaseRequestIsNotClosed() {
        
        List<Case_Request__c> caseRequests = new List<Case_Request__c>
        {
            new Case_Request__c(Subject__c = 'Test Case 1', Description__c = 'Testing case closed 1', Priority__c = 'Medium'),
            new Case_Request__c(Subject__c = 'Test Case 2', Description__c = 'Testing case closed 2', Priority__c = 'Medium'),
            new Case_Request__c(Subject__c = 'Test Case 3', Description__c = 'Testing case closed 3', Priority__c = 'Medium')
        };
        
        
        insert caseRequests;
        
        List<Case_Request__c> casesToUpdate = [SELECT Id, Status__c FROM Case_Request__c LIMIT 3];
        
        Test.startTest();
        casesToUpdate.get(0).Status__c = 'New';
        casesToUpdate.get(1).Status__c = 'In Progress';
        casesToUpdate.get(2).Status__c = 'Escalated';
        
        update casesToUpdate;
        
        List<Case_History__c> caseHistories = [SELECT Id FROM Case_History__c LIMIT 1];
        
        Test.stopTest();
        
        System.assertEquals(true, caseHistories.isEmpty(), 'Case history should not be created.');
    }
}