force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <description>Logging customer support requests.</description>
    <label>Case Request</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Case Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the request.</description>
    <inlineHelpText>Choose the appropriate status for the progress of the request.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReopenCaseRequest.cls
public with sharing class ReopenCaseRequest {
    
    @AuraEnabled
    public static void reopenCase(String caseId, String status) {
        
        if (status == 'Closed') {
            
            Case_Request__c caseToReopen = [SELECT Id, Status__c from Case_Request__c WHERE Id = :caseId WITH SECURITY_ENFORCED];
            caseToReopen.Status__c = 'In Progress';
            update as user caseToReopen;
            
            // Auto-Launched Flow
            Map<String, Object> flowParams = new Map<String, Object>();
            flowParams.put('caseId', caseId);
            
            Flow.Interview autoFlow = Flow.Interview.createInterview('New_SLA_for_reopened_Case', flowParams);
            autoFlow.start();
            
        } else {
            AuraHandledException ae = new AuraHandledException('This Case Request is not closed. You can only reopen closed cases.');
            ae.setMessage('This Case Request is not closed. You can only reopen closed cases.');
            throw ae;
        }
    }
}