force-app/main/default/objects/Case_Request__c/Case_Request__c.object-meta.xml
<CustomObject>
    <description>Logging customer support requests.</description>
    <label>Case Request</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Case Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Full details of the support request.</description>
    <inlineHelpText>Describe the issue encountered with as much detail as possible.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Request priority.</description>
    <inlineHelpText>Select the urgency level of the request.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Support request title.</description>
    <inlineHelpText>Provide a brief summary of the issue.</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Request__c/fields/Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Support_Level__c</fullName>
    <label>Support Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
            <value>
                <fullName>VIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseRequestManagerTest.cls
@isTest
private class CaseRequestManagerTest {
    
    @isTest
    static void testGetCaseRequest() {
        
        Case_Request__c testCase = createCaseRequest();
        String caseId = testCase.Id;
        RestRequest request = new RestRequest();
        
        Test.startTest();
        
        request.requestUri =
            'https://orgfarm-c3dcedbc2f-dev-ed.develop.my.salesforce.com/services/apexrest/Case_Request__c/'
            + caseId;
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        String response = CaseRequestManager.getCaseRequest();
        
        Test.stopTest();
        
        System.assertEquals(true, response != null, 'response should not be null');
        System.assertEquals(true, response.contains('"status" : "New"'), 'response should contain "status"');
        System.assertEquals(true, response.contains('"slaMet" : null'), 'response should contain "slaMet"');
    }
    
    @isTest
    static void testRequestNull() {
        
        Test.startTest();
        
        RestRequest request = null;
        
        String response = CaseRequestManager.getCaseRequest();
        
        Test.stopTest();
        
        System.AssertEquals(true, response.contains('"status" : 400'), 'response should contain status 400');
        System.assertEquals(true, response.contains('"error" : "Bad Request"'), 'response should contain error bad request');
        System.AssertEquals(true, response.contains('"message" : "Invalid request URI."'), 'response should contain message invalid request URI.');
    }
    
    @isTest
    static void testRequestWithIdNull() {
        
        RestRequest request = new RestRequest();
        
        Test.startTest();
        
        request.requestUri =
            'https://orgfarm-c3dcedbc2f-dev-ed.develop.my.salesforce.com/services/apexrest/Case_Request__c/';
        
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        String response = CaseRequestManager.getCaseRequest();
        
        Test.stopTest();
        
        System.debug(response);
        
        System.AssertEquals(true, response.contains('"status" : 400'), 'response should contain status 400');
        System.assertEquals(true, response.contains('"error" : "Bad Request"'), 'response should contain error bad request');
        System.AssertEquals(true, response.contains('"message" : "Case request id can\'t be null."'), 'response should contain message id can\'t be null');
    }
    
    @isTest
    static void testRequestWithIdNotFound() {
        
        RestRequest request = new RestRequest();
        String caseId = '12345';
        
        Test.startTest();
        
        request.requestUri =
            'https://orgfarm-c3dcedbc2f-dev-ed.develop.my.salesforce.com/services/apexrest/Case_Request__c/'
            + caseId;
        
        request.httpMethod = 'GET';
        RestContext.request = request;
        
        String response = CaseRequestManager.getCaseRequest();
        
        Test.stopTest();
        
        System.debug(response);
        
        System.AssertEquals(true, response.contains('"status" : 404'), 'response should contain status 404');
        System.assertEquals(true, response.contains('"error" : "Not Found"'), 'response should contain error not found');
        System.AssertEquals(true, response.contains('"message" : "Case Request ID not found or invalid."'), 'response should contain message id not found');
    }
    
    private static Case_Request__c createCaseRequest() {
        
        Case_Request__c testCase = new Case_Request__c();
        testCase.Subject__c = 'Test Case';
        testCase.Description__c = 'Test Case Description';
        testCase.Priority__c = 'Low';
        testCase.Support_Level__c = 'Basic';
        testCase.RecordTypeId = Schema.SObjectType.Case_Request__c.getRecordTypeInfosByName().get('Premium Support').getRecordTypeId();
        
        insert testCase;
        
        return testCase;
    }
}